### ISSUE TITLE
'aurt' not found

### ISSUE THREAD

**Issue by songhongxiang** [INTO-CPS-Association/aurt#11]
I don't know how to use “aurt” command, please help me

```
test@test-vm:~/Desktop$ aurt --help

Command 'aurt' not found, did you mean:

  command 'art' from deb artemis (17.0.1+dfsg-2)
```

**Comment by EmilMadsen90** [comment]
Have you installed AURT?
`pip install aurt`

**Comment by EmilMadsen90** [comment]
I'm closing this issue as there does not seem to be any issue with installing the AURT software.

**Comment by songhongxiang** [comment]
> Have you installed AURT? `pip install aurt`
I've installed it, but I still can't find "aurt". The installed version is aurt 0.0.4, and python's version is v3.8.2.

**Comment by EmilMadsen90** [comment]
You'll have to provide some more information for me to be able to help. Was the installation successful? Please provide a log or other detailed information.
I've just installed AURT on two different Windows machines, and AURT is installed regularly on Github servers for Windows, Linux, and MacOS. No issues recently.

**Comment by EmilMadsen90** [comment]
I'm glad to hear that it worked out :-)
