### ISSUE TITLE
about the format of measured_data.csv

### ISSUE THREAD

**Issue by jack-sherman01** [INTO-CPS-Association/aurt#14]
thank you for your open source work! 
Could I know the format of "measured_data.csv"?
Or, it would be better if you could share a example file of "measured_data.csv". 
I'd appreciate it!

**Comment by EmilMadsen90** [comment]
Hi @jack-sherman01

Good point, this is not well documented. There are actually two datasets (see below) in the repo, you can have a look at.

**Two-link manipulator dataset**
I do not remember the mounting but either `gravity = [0 0 9.81]` or `gravity = [0 6.9367 -6.9367]`.
https://github.com/INTO-CPS-Association/aurt/blob/master/aurt/tests/resources/twolink_data.csv

**UR5e dataset**
Mounted with a rotation of 45 deg around the x axis, so `gravity = [0 6.9367 -6.9367]`
https://github.com/INTO-CPS-Association/aurt/blob/master/resources/Dataset/ur5e_45degX_aurt_demo_1/ur5e_45degX_aurt_demo_1.csv
